#! /bin/bash
# launch stuff once fluxbox is open
while [ $(ps -e | grep -c fluxbox) -eq 0 ];do
	nitrogen --restore
done
# keep some tray applications alive
while : ;do
	# launch this to keep the desktop background painted	
	nitrogen --restore
	# check for icons in tray to keep active
	if [ $(ps -e | grep -c volumeicon) -eq 0 ];then
		volumeicon &
	fi
	if [ -f /usr/bin/redshift-gtk ];then
		if [ $(ps -e | grep -c redshift-gtk) -eq 0 ];then
			redshift-gtk -l $(cat /etc/latlon) &
		fi
	fi
	if [ -f /usr/bin/nm-applet ];then
		if [ $(ps -e | grep -c nm-applet) -eq 0 ];then
			nm-applet &	
		fi
	else	
		if [ -f /usr/bin/wicd-gtk ];then
			if [ $(ps -e | grep -c wicd-client) -eq 0 ];then
				wicd-gtk --tray &	
			fi
		fi
	fi
	if [ $(ps -e | grep -c kupf) -eq 0 ];then
		kupfer --no-splash &	
	fi
	if [ $(ps -e | grep -c guake) -eq 0 ];then
		guake &
	fi
	# sleep for 30 seconds then check for applets again
	sleep 60
done
