#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "~/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi
# kill apps that start automaticly to fluxbox restart dont fuck stuff up
killall nm-applet
killall volumeicon
killall xbattbar
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
pidgin &
guake &
kupfer --no-splash &
nm-applet &
volumeicon &
# set the background with nitrogen
nitrogen --restore &
# laptop battery indiaator if its a laptop
if laptop-detect;then
	xfce4-power-manager
fi
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"
