#! /bin/bash
# keep some tray applications alive
while : ;do
	# launch this to keep the desktop background painted	
	nitrogen --restore
	# check for icons in tray to keep active
	if ! pgrep volumeicon;then
		volumeicon &
	fi
	if [ -f /usr/bin/redshift ];then
		if ! pgrep redshift;then
			gtk-redshift -l $(cat /etc/latlon) &
		fi
	fi
	if [ -f /usr/bin/nm-applet ];then
		if ! pgrep nm-applet;then
			nm-applet &	
		fi
	else	
		if [ -f /usr/bin/wicd-gtk ];then
			if ! pgrep wicd-client;then
				wicd-gtk --tray &	
			fi
		fi
	fi
	if ! pgrep kupf;then
		kupfer --no-splash &	
	fi
	if ! pgrep guake;then
		guake &
	fi
	# sleep for 60 seconds then check for applets again
	sleep 60
done
